spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  mail:
    properties:
      debug: 'true'
      mail:
        smtp:
          starttls:
            enable: 'true'
          ssl:
            trust: smtp.naver.com
            enable: 'true'
          auth: 'true'
    host: smtp.naver.com
    username: spphire2@naver.com
    password: nette74
    port: '465'

server:
  port: 8084



